### ISSUE TITLE
OGPについて

### ISSUE THREAD

**Issue by keitakawamoto** [monochromegane/hugo-theme-thinking-megane#2]
今OGP関連は  `og:image` は指定していますが、それ以外は指定していません。
リンクを貼り付けた時にFacebookなどでは勝手にタイトルや本文冒頭も表示してくれるのですが、Slackでは `og:image` 部分しか表示されず、タイトル・本文冒頭が表示されずわかりにくいです。

| Facebook | Slack |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/1661325/8638275/0b1dfbda-28f1-11e5-92e9-4be4cb55f0c7.png) | ![image](https://cloud.githubusercontent.com/assets/1661325/8638274/f7f1b696-28f0-11e5-9c08-4943d2acaaa4.png) |

```
<meta property="og:title" content="{{ .そのページのtitle（記事ページなら記事名も入っている状態）を出力する書き方}}">
<meta property="og:description" content="{{ .そのページの冒頭を出力する書き方}}">
<meta property="og:url" content="{{ .そのページのURLを出力する書き方}}">
```

このように指定できたら理想的かもしれません。
う〜〜〜〜ん。ありますかね。。。

**Comment by monochromegane** [comment]
なるほど〜

> そのページのtitle

```
{{ .Title }}
```

でよさそう

> そのページの冒頭を出力する書き方

うーん、ちょっと調べます

> そのページのURLを出力する書き方

```
{{ .Permalink }}
```

でよさそう〜

**Comment by monochromegane** [comment]
> そのページの冒頭を出力する書き方

ひとまず http://gohugo.io/content/summaries/ にあるように

```
{{ . Summary }}
```

を使ってみますか。自動で切り出すので完全に記事は途中で切れるけど

エントリ書く度に

```
<!--more-->
```

を入れていくのはちょっと面倒そうなので。

**Comment by keitakawamoto** [comment]
https://github.com/keitakawamoto/hugo-theme-thinking-megane/commit/b778d9101495e7832c384bcce960d015a4a7cdeb

実装してみました。
が、しかし...

> Cons: All HTML tags are stripped from the summary, and the first 70 words, whether they belong to a heading or to different paragraphs, are all lumped into one paragraph. Some people like it, but some people don’t.

`{{ .Summary }}` はすべてのHTMLタグが除去、と書いてあるのに、htmlが出力され、見た目が大変なことになってしまいました。

| コード | 見た目 |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/1661325/8654277/4a1ee6d6-29c4-11e5-9b7e-dfef69717b7a.png) | ![image](https://cloud.githubusercontent.com/assets/1661325/8654256/329d7536-29c4-11e5-930f-ce3aa3a53ea7.png) |

`{{ .Summary }}` を省くと、うまくいきました。

![image](https://cloud.githubusercontent.com/assets/1661325/8654304/727e5ddc-29c4-11e5-8e0b-9d2782a04eef.png)

最悪、`og:title` があれば内容はわかるので、`og:description` はナシでもいい...？

**Comment by keitakawamoto** [comment]
@monochromegane と口頭で検討したところ、`og:description` は実装しないことになった。
